### Get todas as salas de aula GET http://localhost:40000/salasdeaula HTTP/1.1 Content-Type: application/json

### Get sala de aula por ID GET http://localhost:40000/salasdeaula/1 HTTP/1.1 Content-Type: application/json

### Inserir nova sala de aula POST http://localhost:40000/salasdeaula HTTP/1.1 Content-Type: application/json

{
    "descricao": "Sala 105", "localizacao": "Bloco B", "capacidade": 30

}

### Atualizar sala de aula existente PUT http://localhost:40000/salasdeaula/1 HTTP/1.1 Content-Type: application/json

{
    "descricao": "Sala 102", "localizacao": "Bloco D", "capacidade": 40

}

### Deletar (soft delete) sala de aula DELETE http://localhost:40000/salasdeaula/1 HTTP/1.1 Content-Type: application/json
